//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Course.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderLine = new HashSet<OrderLine>();
        }
    [Required]
        public int ProductId { get; set; }
    [Required]
    public string ProductName { get; set; }
    [Required]
        [Range(2,99,ErrorMessage="2~99之間")]
        [DisplayFormat(DataFormatString="{0:C}")]
    public Nullable<decimal> Price { get; set; }
    [Required]
    public Nullable<bool> Active { get; set; }
    [Required]
    public Nullable<decimal> Stock { get; set; }
    
        public virtual ICollection<OrderLine> OrderLine { get; set; }
    }
}
